@startuml
object Program

object Node {
  Accept(NodeVisitor)
}

note "v --> VisitAssignement(this)" as N1
AssignementNode .. N1
object AssignementNode{
  Accept(NodeVisitor v)
}

note "v --> VisitVariableRef(this)" as N2
VariableRefNode .. N2
object VariableRefNode{
  Accept(NodeVisitor v)
}

Program o-- "*" Node
Node <|-- AssignementNode
Node <|-- VariableRefNode

object NodeVisitor {
  VisitAssignement(AssignementNode)
  VisitVariableRef(VariableRefNode)
}

object TypeCheckingVisitor {
  VisitAssignement(AssignementNode)
  VisitVariableRef(VariableRefNode)
}

object CodeGeneratingVisitor {
  VisitAssignement(AssignementNode)
  VisitVariableRef(VariableRefNode)
}

NodeVisitor <|-- TypeCheckingVisitor
NodeVisitor <|-- CodeGeneratingVisitor
@enduml